name: Build

# set criteria
on: [pull_request]

jobs:
  Test:
    # select the OS
    runs-on: ubuntu-20.04
    steps:
      # use actions
      - uses: actions/checkout@v2

      - name: Print version
        run: node -v && npm -v && yarn -v

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Run Tests
        run: yarn test
